/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        light: {
          "color-scheme": "light",
          "primary": "#50c878",
          "primary-content": "#0a2614",
          "secondary": "#72001c",
          "secondary-content": "#fff8f8",
          "accent": "#72001c",
          "accent-content": "#fff8f8",
          "neutral": "#2a4a34",
          "neutral-content": "#f5f7f2",
          "base-100": "#fdfdf8",
          "base-200": "#f7f7f2",
          "base-300": "#edeee6",
          "base-content": "#1a1a1a",
          "info": "#0ea5e9",
          "info-content": "#f8fcff",
          "success": "#22c55e",
          "success-content": "#f5fdf7",
          "warning": "#a8910f",
          "warning-content": "#1a1600",
          "error": "#ef4444",
          "error-content": "#fff8f7",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.5rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
        dark: {
          "color-scheme": "dark",
          "primary": "#50c878",
          "primary-content": "#0a2614",
          "secondary": "#72001c",
          "secondary-content": "#f9ffea",
          "accent": "#72001c",
          "accent-content": "#f9ffea",
          "neutral": "#143e22",
          "neutral-content": "#f5f7f2",
          "base-100": "#120612",
          "base-200": "#120612",
          "base-300": "#1c2c37",
          "base-content": "#e5e5e5",
          "info": "#38bdf8",
          "info-content": "#0c1a25",
          "success": "#4ade80",
          "success-content": "#0d2618",
          "warning": "#cfae2b",
          "warning-content": "#000000",
          "error": "#f87171",
          "error-content": "#1f0a0a",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.5rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
}
