/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelloSearchRouteImport } from './routes/hello-search'
import { Route as StudioIndexRouteImport } from './routes/studio/index'

const HelloSearchRoute = HelloSearchRouteImport.update({
  id: '/hello-search',
  path: '/hello-search',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/hello-search': typeof HelloSearchRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/hello-search': typeof HelloSearchRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/hello-search': typeof HelloSearchRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/hello-search' | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/hello-search' | '/studio'
  id: '__root__' | '/hello-search' | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HelloSearchRoute: typeof HelloSearchRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello-search': {
      id: '/hello-search'
      path: '/hello-search'
      fullPath: '/hello-search'
      preLoaderRoute: typeof HelloSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HelloSearchRoute: HelloSearchRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
